CREATE TABLE IF NOT EXISTS weather_raw_staging (
    id                   BIGSERIAL    PRIMARY KEY,
    "timestamp"          VARCHAR(50),
    temperature_2m       NUMERIC,
    relative_humidity_2m NUMERIC,
    precipitation        NUMERIC,
    rain                 NUMERIC,
    snowfall             NUMERIC,
    weather_code         SMALLINT,
    cloud_cover          NUMERIC,
    wind_speed_10m       NUMERIC,
    wind_direction_10m   NUMERIC,
    wind_gusts_10m       NUMERIC,
    surface_pressure     NUMERIC,
    visibility           NUMERIC,
    uv_index             NUMERIC,
    is_day               SMALLINT,
    location_name        VARCHAR(100),
    location_country     VARCHAR(100),
    latitude             NUMERIC(9,6),
    longitude            NUMERIC(9,6),
    extracted_at         VARCHAR(50),
    loaded_at            TIMESTAMPTZ  DEFAULT NOW(),
    is_processed         BOOLEAN      DEFAULT FALSE
);
